from .molmo2_video_caption import NODE_CLASS_MAPPINGS as MOLMO_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MOLMO_DISPLAY
from .video_caption_gguf import NODE_CLASS_MAPPINGS as GGUF_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GGUF_DISPLAY

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(MOLMO_MAPPINGS)
NODE_CLASS_MAPPINGS.update(GGUF_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(MOLMO_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(GGUF_DISPLAY)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
